### ISSUE TITLE
9: Implementation of toggle type form element

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-utils-library#10]
## Description
Implement the toggle question in the dynamic form. All the configurations (placeholder, validation, layout, etc) required for the rendering of toggle questions should be configurable using JSON.

## Goals
- [ ] Create an interface for the base form object.
- [ ] Install angular material as the dependency for the library
- [ ] As per the reference implementation, convert the code to handle the angular material input component.
- [ ] Implement the test cases for the component
- [ ] Prepare proper documentation for the implementation

## Acceptance Criteria
- [ ] Should be able to render the form with a toggle type form element

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the forms can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-Library

### Project Name
SL-Library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by sDwivede** [comment]
comment

**Comment by SanjayRam07** [comment]
hello @kiranharidas187  , can I work on this issue?
Could you please assign and mentor me?

**Comment by nikhil061102** [comment]
Sir, I am interested and have some doubts.
How should it look (are there any UI designs/patterns)
Please let me know.

**Comment by sid-nc** [comment]
@kiranharidas187 Can I get assigned to this

**Comment by prakhardotdeb** [comment]
hello @kiranharidas187 sir! I feel i have the skills required for this project and i would love to contributr. Could you please assign this ticket to me?

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by aryangandhi05** [comment]
Hare Krishna @kiranharidas187 Sir I want to solve this issue, as i understand it, and i will give my 100% for solving this issue So please, can you assign me this?

**Comment by ishaaaa8** [comment]
Hi @kiranharidas187 , I'm interested in contributing to this issue. Could you please grant me permission to work on it? Thanks!

**Comment by abansal15** [comment]
hello @kiranharidas187 could you please assign the issue to me ?

**Comment by PayalKumari10** [comment]
@kiranharidas187  i want to work on this issue plz assign me

**Comment by 2003sidd** [comment]
@kiranharidas187 Sir I want to solve this issue so Could you please assign this to me.
Thank you.

**Comment by Goldypatel** [comment]
I definetly would like to work on it. Having experience with rendering forms in previous projects, I certaily believe i can work on this as well

**Comment by harshsrivastav8055** [comment]
Hey can you assign me this issue i have required tech-stack to solve this issue

**Comment by Vi-shub** [comment]
Dear @kiranharidas187,

I am excited to propose the implementation of a toggle question feature in the dynamic form builder library. This enhancement will empower users to include toggle-type form elements with configurable properties such as placeholder, validation rules, and layout specifications.

Key Highlights:
->Introduce an interface for the base form object to define toggle questions' configurations.
->Integrate Angular Material as a dependency to leverage its toggle switch component for rendering toggle questions.
->Refactor code to handle Angular Material input components specifically for toggle questions.
->Develop comprehensive test cases and documentation to ensure the feature's reliability and usability.

Implementation Steps:

->Define the interface structure for the base form object, including properties like type, label, placeholder, isRequired, validationRules, and layout.
->Install Angular Material and import necessary components such as MatSlideToggleModule to enable toggle switch functionality.
->Update the form builder logic to handle toggle questions based on the defined interface structure.
->Implement data binding and event handling for toggle questions to capture user input and perform validation checks.
->Write unit and integration test cases using testing frameworks like Jasmine and Karma to validate the toggle question feature's functionality.
->Prepare detailed documentation outlining the usage of toggle questions, configuration options, and integration with Angular Material within the dynamic form builder.

I believe this enhancement aligns with our goal of providing a versatile and user-friendly form builder experience. I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?
