### ISSUE TITLE
10: Implementation of select type form element

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-utils-library#11]
## Description
Implement the select question in the dynamic form. All the configurations (placeholder, validation, layout, etc) required for the rendering of select form should be configurable using JSON.

## Goals
- [ ] Create an interface for the base form object.
- [ ] Install angular material as the dependency for the library
- [ ] As per the reference implementation, convert the code to handle the angular material input component.
- [ ] Implement the test cases for the component
- [ ] Prepare proper documentation for the implementation

## Acceptance Criteria
- [ ] Should be able to render the form with a select type form element

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the forms can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-Library

### Project Name
SL-Library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by sivangbagri** [comment]
@kiranharidas187 Hii can I work on this??

**Comment by jaivardhan-bhola** [comment]
Hi, Can i work on this? @kiranharidas187

**Comment by SanjayRam07** [comment]
hello @kiranharidas187  , can I work on this issue?
Could you please assign and mentor me?

**Comment by Yuji-Itadorii** [comment]
Hi, Can I work on this? @kiranharidas187

**Comment by sid-nc** [comment]
Can I get assigned to this @kiranharidas187

**Comment by sheffalee** [comment]
@kiranharidas187 sir can u assign me this task as it matches my skill sets and i would like to contribute to this project

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by vilol-04** [comment]
@kiranharidas187 I would like to work on this issue.

**Comment by PayalKumari10** [comment]
@kiranharidas187  i want to work on this issue plz assign me

**Comment by LavanyaaCSE** [comment]
Hello @kiranharidas187 ,
I am interested in working on this issue; could you please assign it to me? I have prior experience working with HTML, CSS and Angular. It would be a great opportunity for me to contribute to this issue. Can you please assign me a task

**Comment by Meet012** [comment]
Hi @kiranharidas187,

I hope you're doing well! I've been eyeing this particular issue and I'm eager to take it on. With my background in HTML, CSS, and Angular, I believe I can make a valuable contribution. Could you please assign this task to me? It would be a fantastic opportunity for me to leverage my skills and help improve this aspect of our project.

Looking forward to your response!

Best regards,
Meet Parmar
