### ISSUE TITLE
11: Implementation of rating type form element

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-utils-library#12]
## Description
Implement the rating type form type in the dynamic form. All the configurations (placeholder, validation, layout, etc) required for the rendering of the rating type form should be configurable using JSON.

## Goals
- [ ] Create an interface for the base form object.
- [ ] Install angular material as the dependency for the library
- [ ] As per the reference implementation, convert the code to handle the angular material input component.
- [ ] Implement the test cases for the component
- [ ] Prepare proper documentation for the implementation

## Acceptance Criteria
- [ ] Should be able to render the form with a  rating type form element

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the forms can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-Library

### Project Name
SL-Library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by SanjayRam07** [comment]
hello @kiranharidas187 , can I work on this issue?
Could you please mentor me?

**Comment by nikhil061102** [comment]
Sir, I am interested and have some doubts.
1. How should it look (are there any UI designs/patterns)
Please let me know.

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by manishpra1996** [comment]
@kiranharidas187 
Sir, I have gone through this problem & feel that I have the required skillset to contribute. Can I work on this?

**Comment by BrahmjotSinghsingh** [comment]
@kiranharidas187 I understand the problem and have a good grasp of the required skillset, would greatly appreciate to work on the project. Could you please assign this to me ?

**Comment by RishabhAnand04** [comment]
Would love to contribute, could you please assign this to me ?

**Comment by aishalxgupta** [comment]
Hi @kiranharidas187 
I'm confident in my understanding of the problem and possess the necessary skills. I'd be grateful for the opportunity to be assigned to this project

**Comment by Nitin8426** [comment]
Hi @kiranharidas187
I have clearly understand the problem and possess the necessay skills and have setup the environment . kindly assign the project . it would be great opportunity

**Comment by heyhimansh** [comment]
Hi @kiranharidas187 ,
I'd like to express my interest in working on the implementation of the rating type form in the dynamic form project. I believe I can contribute effectively to this task based on my experience and skills.

**Comment by PayalKumari10** [comment]
@kiranharidas187  i want to work on this issue plz assign me

**Comment by Abchoudhary2512** [comment]
Hello @kiranharidas187 sir , please assign me this task.
