### ISSUE TITLE
12:  Build and deployment automation scripts

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-utils-library#13]
## Description
Implement a build script to create a build and push the package to the npm repo

## Goals
- [ ]  Should be able to build and deploy the library

## Acceptance Criteria
- [ ]   Should be able to build and deploy the library

## Implementation Details
Angular,Nodejs

## Mockups / Wireframes
NA

### Product Name
SL-Library

### Project Name
SL-Library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, Nodejs

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by sDwivede** [comment]
comment

**Comment by Gmin2** [comment]
Hey @kiranharidas187 would love to work on it

**Comment by SanjayRam07** [comment]
hello @kiranharidas187  , can I work on this issue?
Could you please assign and mentor me?

**Comment by MjStar24** [comment]
hello @kiranharidas187 I would like to work on this project can you assign this to me

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187  I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by PayalKumari10** [comment]
@kiranharidas187  i want to work on this issue plz assign me

**Comment by PayalKumari10** [comment]
Hey @amarts,

I'm interested in contributing to the SL-auth-library project by Shikshalokam. The goal is to implement a build script to create a build and push the package to the npm repo. Additionally, we need to create a test to assert that a message already exists and add this test to the network-score folder, ensuring it passes Build, Cargo, and the test mentioned in the Readme.md.
Please assign this issue to me so I can get started. Thank you!

**Comment by VedantKhairnar** [comment]
Hello @PayalKumari10 
Are you still interested in working on the issue?

If yes, @kiranharidas187 
Will you pls assign it to her?

Thanks.

**Comment by PayalKumari10** [comment]
yes @VedantKhairnar, I am interested in working on this issue.

**Comment by VedantKhairnar** [comment]
Hello @PayalKumari10 
If so, pls directly raise the PR.
Thanks.

**Comment by kiranharidas187** [comment]
This issue is no longer required
