### ISSUE TITLE
1: Base structure for the library

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-utils-library#2]
## Description
This library will contain multiple npm package codes, one being the form library. Create a base structure for the sl-forms library. This repo also should have a reference implementation of the features built in the library. Create an angular application in the same repo with routing. One of the routes should show the implementation of sl-forms

## Acceptance Criteria
- [ ] Repo should have a base structure for sl-forms
- [ ] Repo should have a page to showcase the features of sl-forms

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the forms can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-Library

### Project Name
SL-Library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Low

### Category
Features

### Sub Category
Frontend, Library

**Comment by KDwevedi** [comment]
comment

**Comment by sDwivede** [comment]
comment

**Comment by Debatreya** [comment]
@kiranharidas187 I would like to know more about the project. I am eager to contribute in this, where to start?

**Comment by ayku686** [comment]
This project looks exciting. I would like to work on this project. Can you guide me more on this??

**Comment by priyakumari02** [comment]
@Debatreya  , Can I work on this issue , I believe tech-skills of this project aline to my skills

**Comment by mandirakshetty** [comment]
hey @kiranharidas187 i would like to work on this issue

**Comment by mandirakshetty** [comment]
@kiranharidas187 sir i have worked on this issue below are the images of the base structure i have created , i needed somemore clarity over this for now i am attaching the draft link of the code . 
https://github.com/mandirashetty/sl-form 


![image](https://github.com/ELEVATE-Project/frontend-utils-library/assets/152503252/b9c2f554-3be8-4d72-8cef-2046a3c20c0b)
![image](https://github.com/ELEVATE-Project/frontend-utils-library/assets/152503252/50cbfd57-9f41-47bb-99dc-5f100b43d2af)
![image](https://github.com/ELEVATE-Project/frontend-utils-library/assets/152503252/aba04ca7-c83f-4522-82b3-3738efe5b7bd)
![image](https://github.com/ELEVATE-Project/frontend-utils-library/assets/152503252/258c02c7-ad2d-439b-a296-fc85b97e72c9)

**Comment by Sumsum1231** [comment]
Greetings @kiranharidas187 @5Amogh, 
I have raised the PR https://github.com/ELEVATE-Project/frontend-utils-library/pull/15 kindly review it.

**Comment by aryangandhi05** [comment]
Hare Krishna @kiranharidas187 
Sir I want to solve this issue, as i understand it, and i will give my 100% for solving this issue So please, can you assign me this?

**Comment by manishpra1996** [comment]
@kiranharidas187 
Sir, I have gone through this problem & feel that I have the required skillset to contribute. Can I work on this?

**Comment by tanishkagupta27** [comment]
@kiranharidas187 
Sir, I want to work on this project. I have knowledge of HTML, CSS and Angular. I have also made some projects in these tech stacks. Can you please assign me this.

**Comment by Anushreebasics** [comment]
@kiranharidas187 I want to work on this project, kindly assign it to me

**Comment by NkSailesh** [comment]
@kiranharidas187  It sounds good.  I would like to know more about the project, I am Intrested  to contribute in this. where I can start?

**Comment by praxcodes** [comment]
@kiranharidas187 Hey, I would like to contribute to this issue, can you tell me how to proceed?

**Comment by Almas456** [comment]
@kiranharidas187 I think I have the skill set to work on this issue. Please sign this task for me.

**Comment by nithamitabh** [comment]
Kindly! explain me How I can contribute to project is any existing code already written or I have to write from scratch

**Comment by debangi29** [comment]
Hello, I would like to work on this issue.. this aligns with my tech stack :)

**Comment by Blacksujit** [comment]
@kiranharidas187 

I can solve this issue and can also collaborate with others please assign this issue to me
