### ISSUE TITLE
2: Implement the Text type question

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-utils-library#3]
## Description
Implement the text-type question in the dynamic form. All the configurations (placeholder, validation, layout, etc) required for the rendering of text questions should be configurable using JSON.

## Goals
- [ ] Create an interface for the base question type.
- [ ] Install angular material as the dependency for the library
- [ ] As per the reference implementation, convert the code to handle the angular material input component.
- [ ] Implement the test cases for the component
- [ ] Prepare proper documentation for the implementation

## Acceptance Criteria
- [ ] Should be able to render the form with text type form element

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the forms can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-Library

### Project Name
SL-Library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by Shruti3004** [comment]
test

**Comment by sDwivede** [comment]
comment

**Comment by ranjanmangla1** [comment]
Hi @kiranharidas187 , can you assign me this issue? I would love to work on it

**Comment by Riyaasharma** [comment]
@kiranharidas187 @Shruti3004 Greetings, I have gone through the goals which to be achieved mentioned above and also I understood the problem statement, Can you please assign this ticket to me?

**Comment by riasharmma** [comment]
@kiranharidas187 @Shruti3004 Greetings, I have gone through the goals which to be achieved mentioned above and also I understood the problem statement, Can you please assign this ticket to me?

**Comment by SanjayRam07** [comment]
hello @kiranharidas187 , @Shruti3004  , can I work on this issue?
Could you please assign and mentor me?

**Comment by Sandeep0306** [comment]
Hi @kiranharidas187 i would like to work on this issue. can you assign this to me?

**Comment by sheffalee** [comment]
@kiranharidas187 can u assign me this task as it matches my skill sets and i would like to contribute to this

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by abhinavnandekar** [comment]
@kiranharidas187 I am an angular developer and I can solve the problem. Assign me this, so that I get a chance to work on the project.

**Comment by akashsingh011** [comment]
Hello, @kiranharidas187, I would like to contribute to this project. I have the required skillset for it. Please assign me to the task so I can proceed with the development.

**Comment by summerpun2803** [comment]
@kiranharidas187 can i work on this issue

**Comment by swrno** [comment]
Hello @kiranharidas187!
just a clarification question: do we have to submit the PR at [release-1.0.0](https://github.com/ELEVATE-Project/frontend-utils-library/tree/release-1.0.0) branch ? because the main is empty :)

**Comment by Vinod-V3** [comment]
Hey @Swarnendu0123
Yes, you have to raise the PR to the release-1.0.0 branch

**Comment by swrno** [comment]
> Hey @Swarnendu0123
> Yes, you have to raise the PR to the release-1.0.0 branch

Cool, got it!

**Comment by kabir-afk** [comment]
@kiranharidas187 the link you have provided doesn't seem to contain any wireframe/design we are supposed to refer to

**Comment by VivekPrakashNitH** [comment]
@kiranharidas187 @abhinavnandekar is the work still open ? can i get assigned to it

**Comment by LavanyaaCSE** [comment]
Hello @kiranharidas187 , 
I am interested in working on this issue; could you please assign it to me? I have prior experience working with HTML, CSS and Angular. It would be a great opportunity for me to contribute to this issue. Can you please assign me a task

**Comment by ArchitJ6** [comment]
Hi @kiranharidas187,
I've reviewed the issue and believe my skillset aligns well to contribute. Can I work on this?

**Comment by ghost** [comment]
Hlo myself rishita i want to work on this issue i have a keen interest toward css and html. Please give me some task.

**Comment by ishitamaura** [comment]
Hello @kiranharidas187 I am interested to work on the issue. I request you to assign the task.
