### ISSUE TITLE
3: Implementation of radio type form element

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-utils-library#4]
## Description
Implement the radio-type question in the dynamic form. All the configurations (placeholder, validation, layout, etc) required for the rendering of radio questions should be configurable using JSON.

## Goals
- [ ] Create an interface for the base form object.
- [ ] Install angular material as the dependency for the library
- [ ] As per the reference implementation, convert the code to handle the angular material input component.
- [ ] Implement the test cases for the component
- [ ] Prepare proper documentation for the implementation

## Acceptance Criteria
- [ ] Should be able to render the form with radio-type form element

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the forms can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-Library

### Project Name
SL-Library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by sDwivede** [comment]
comment

**Comment by ranjanmangla1** [comment]
Hi @kiranharidas187 , can you assign me this issue? I would love to work on it

**Comment by anand-242** [comment]
@kiranharidas187 @Shruti3004 Greetings, I am interested in contributing to this project. I have been following the development closely and am eager to contribute my skills and expertise. Can you please assign me this ticket?

**Comment by yashvikram30** [comment]
Hello ma'am @kiranharidas187 I am interested to contributing to this project. Will you oblige to assign me the same? Looking forward for working under your guidance.

**Comment by Y3ABHISHEK** [comment]
@anand-242 @ranjanmangla1 @yashvikram30 

https://meet.google.com/xvv-ccjc-duv
You can join the standup at 6:30 PM today to get this ticket!

**Comment by SanjayRam07** [comment]
hello @kiranharidas187  , can I work on this issue?
Could you please assign and mentor me?

**Comment by ananyam23** [comment]
Hello ma'am @kiranharidas187  I am interested to contributing to this project. Will you oblige to assign me the same? Looking forward for working under your guidance.

**Comment by KRITIKA453** [comment]
hi can you assign this to me?

**Comment by sid-nc** [comment]
@kiranharidas187 Can I get assigned to this

**Comment by sheffalee** [comment]
@kiranharidas187 can u assign me this task

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by aryangandhi05** [comment]
Hello @kiranharidas187 
Sir I want to solve this issue, as i understand it, and i will give my 100% for solving this issue So please, can you assign me this?

**Comment by tanishkagupta27** [comment]
Hi @kiranharidas187 
I understand this issue, I would like to work on this, can you please assign me this issue?

**Comment by Guptasameer533** [comment]
Hi @kiranharidas187, I have read the project description in detail.

Therefore, as an experienced **Angular developer**, I possess the requisite skills to implement **the project demand** and **API flows** effectively. My expertise lies in crafting **responsive designs**, **seamlessly integrating with APIs**, and conducting **comprehensive testing**. I am committed to delivering high-quality work that adheres to the project's standards.

Furthermore, I am eager to **collaborate** closely with the team to ensure a successful implementation of this feature.

**Comment by PayalKumari10** [comment]
@kiranharidas187  i want to work on this issue plz assign me
