### ISSUE TITLE
4: Implementation of checkbox type form element

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-utils-library#5]
## Description
Implement the checkbox-type question in the dynamic form. All the configurations (placeholder, validation, layout, etc) required for the rendering of checkbox questions should be configurable using JSON.

## Goals
- [ ] Create an interface for the base form object.
- [ ] Install angular material as the dependency for the library
- [ ] As per the reference implementation, convert the code to handle the angular material input component.
- [ ] Implement the test cases for the component
- [ ] Prepare proper documentation for the implementation

## Acceptance Criteria
- [ ] Should be able to render the form with a checkbox-type form element

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the forms can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-Library

### Project Name
SL-Library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by sDwivede** [comment]
comment

**Comment by SilverDragonOfR** [comment]
Hi! @kiranharidas187, I am interested to work in project. Can you please refer me how to set this project up locally and contribute to it ?

**Comment by Sandeep0306** [comment]
Hi @kiranharidas187 , I'm interested in working on this issue. Can you assign it to me?

**Comment by jaivardhan-bhola** [comment]
Hi, Can i work on this? @kiranharidas187

**Comment by yashvikram30** [comment]
Hello maam @kiranharidas187 . I have read through the details and am interested to contribute to the same! Looking forward for working under your mentorship and guidance.

**Comment by SanjayRam07** [comment]
hello @kiranharidas187  , can I work on this issue?
Could you please assign and mentor me?

**Comment by Yuji-Itadorii** [comment]
hello @kiranharidas187, can I work on this issue?

**Comment by sid-nc** [comment]
@kiranharidas187 Can I get assigned to this

**Comment by prakhardotdeb** [comment]
hello @kiranharidas187  sir! I feels i have skills required for this project and i would love to contributr. Could you please assign this ticket to me?

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by aryangandhi05** [comment]
Hare Krishna @kiranharidas187  Sir i want to solve this issue, as i understand it, and i will give my 100% for solving this issue So please, can you assign me this?

**Comment by kovida09** [comment]
Hey @kiranharidas187 . I have read and understood the problem . I am interested to work on this project …

**Comment by Guptasameer533** [comment]
Hi @kiranharidas187, I have read the project description in detail.

Therefore, as an experienced **Angular developer**, I possess the requisite skills to implement **the project demand** and **API flows** effectively. My expertise lies in crafting **responsive designs**, **seamlessly integrating with APIs**, and conducting **comprehensive testing**. I am committed to delivering high-quality work that adheres to the project's standards.

Furthermore, I am eager to **collaborate** closely with the team to ensure a successful implementation of this feature.
