### ISSUE TITLE
5: Implementation of chip type form element

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-utils-library#6]
## Description
Implement the chip-type question in the dynamic form. All the configurations (placeholder, validation, layout, etc) required for the rendering of radio questions should be configurable using JSON.

## Goals
- [ ] Create an interface for the base form object.
- [ ] Install angular material as the dependency for the library
- [ ] As per the reference implementation, convert the code to handle the angular material input component.
- [ ] Implement the test cases for the component
- [ ] Prepare proper documentation for the implementation

## Acceptance Criteria
- [ ] Should be able to render the form with a chip-type form element

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the forms can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-Library

### Project Name
SL-Library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by sDwivede** [comment]
comment

**Comment by SanjayRam07** [comment]
hello @kiranharidas187  , can I work on this issue?
Could you please assign and mentor me?

**Comment by nikhil061102** [comment]
Sir, I am interested and have some doubts.
1. Are you talking about something like this : [link](https://chakra-ui.com/docs/components/tag/usage#with-custom-element)
2. How should it look (are there any UI designs/patterns)
Please let me know.

**Comment by sid-nc** [comment]
@kiranharidas187 Can I get assigned to this issue

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by soumya-maheshwari** [comment]
hi @kiranharidas187 
I'm interested in working on this issue and would appreciate some guidance on how to get started.

**Comment by Guptasameer533** [comment]
Hi @kiranharidas187, I have read the project description in detail.

Therefore, as an experienced **Angular developer**, I possess the requisite skills to implement **the project demand** and **API flows** effectively. My expertise lies in crafting **responsive designs**, **seamlessly integrating with APIs**, and conducting **comprehensive testing**. I am committed to delivering high-quality work that adheres to the project's standards.

Furthermore, I am eager to **collaborate** closely with the team to ensure a successful implementation of this feature.
