### ISSUE TITLE
6: Implementation of slider type form element

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-utils-library#7]
## Description
Implement the slider-type question in the dynamic form. All the configurations (placeholder, validation, layout, etc) required for the rendering of slider questions should be configurable using JSON.

## Goals
- [ ] Create an interface for the base form object.
- [ ] Install angular material as the dependency for the library
- [ ] As per the reference implementation, convert the code to handle the angular material input component.
- [ ] Implement the test cases for the component
- [ ] Prepare proper documentation for the implementation

## Acceptance Criteria
- [ ] Should be able to render the form with a slider-type form element

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the forms can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-Library

### Project Name
SL-Library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by sDwivede** [comment]
Comment

**Comment by shivam-Purohit** [comment]
hey @kiranharidas187 I was looking forward to contribute to this project. Is there anything I can help with?

**Comment by jaivardhan-bhola** [comment]
Hi, Can i work on this? @kiranharidas187

**Comment by SanjayRam07** [comment]
hello @kiranharidas187  , can I work on this issue?
Could you please assign and mentor me?

**Comment by sid-nc** [comment]
@kiranharidas187 Can I get assigned to this?

**Comment by prakhardotdeb** [comment]
hello @kiranharidas187 sir! I feels i have skills required for this project and i would love to contributr. Could you please assign this ticket to me?

**Comment by Naval284** [comment]
Hi @kiranharidas187 , I have gone through the goals to be achieved mentioned above and also I understood the problem statement, I am interested in being part of this project, Can you please assign this ticket to me?

**Comment by Singh-Supreet** [comment]
@kiranharidas187  I am very confident that I will be able to do this efficiently. I have a lot of experience in making responsive websites. Looking forward to discussing with you

**Comment by sheffalee** [comment]
@kiranharidas187 can u assign me this task i would love to do this as it matches my skill stack

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by aryangandhi05** [comment]
Hello @kiranharidas187 
Sir i want to solve this issue, as i understand it, and i will give my 100% for solving this issue So please, can you assign me this?

**Comment by Lahu19** [comment]
Hello there,
Since I think I can meet the project's requirements and because I have already contributed a PR showcasing my abilities, I would like to offer assistance with the Implementation of slider type form element. 

the landing page of https://github.com/Code4GovTech and pull (3) 
I'll be waiting to hear back.

**Comment by PayalKumari10** [comment]
@kiranharidas187  i want to work on this issue plz assign me
