### ISSUE TITLE
8: Implementation of text-area type form element

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-utils-library#9]
## Description
Implement the text-area question in the dynamic form. All the configurations (placeholder, validation, layout, etc) required for the rendering of text-area questions should be configurable using JSON.

## Goals
- [ ] Create an interface for the base form object.
- [ ] Install angular material as the dependency for the library
- [ ] As per the reference implementation, convert the code to handle the angular material input component.
- [ ] Implement the test cases for the component
- [ ] Prepare proper documentation for the implementation

## Acceptance Criteria
- [ ] Should be able to render the form with a text-area type form element

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the forms can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-Library

### Project Name
SL-Library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by sDwivede** [comment]
comment

**Comment by sDwivede** [comment]
comment

**Comment by yashvikram30** [comment]
Hello maam @kiranharidas187 . I have read through the details and am interested to contribute to the same! Looking forward for working under your mentorship and guidance.

**Comment by SanjayRam07** [comment]
hello @kiranharidas187  , can I work on this issue?
Could you please assign and mentor me?

**Comment by Sandeep0306** [comment]
Hi @kiranharidas187 i would like to work on this issue. can you assign this to me?

**Comment by SanjayRam07** [comment]
@kiranharidas187 , here's my workflow:
### Step 1: Set Up Angular Project

1. **Create Angular Project:**
   - Use Angular CLI to create a new project.

2. **Install Angular Material:**
   - Install Angular Material as a dependency using the following command:

### Step 2: Define Interface and Base Form Object

3. **Create Interface for Base Form Object:**
   - Define an interface for the base form object that includes properties like `type`, `label`, `placeholder`, `validation`, etc.

### Step 3: Convert Code to Use Angular Material

4. **Convert Code for Text-Area Question:**
   - Modify the code to handle Angular Material input component for the text-area question.

### Step 4: Configurability Using JSON

5. **Configure Using JSON:**
   - Create a configuration mechanism to handle JSON configurations for text-area questions.
   - Allow configurations for placeholder, validation rules, layout, etc., through JSON.

### Step 5: Implement Test Cases

6. **Write Test Cases:**
   - Implement unit tests for the text-area question component.
   - Cover scenarios such as rendering, validation, and interactions.

### Step 6: Documentation

7. **Prepare Documentation:**
   - Document the interface for the base form object.
   - Explain the JSON configurations and their usage for text-area questions.
   - Document the steps for integrating and using the SL-Library in other Angular projects.

### Step 7: Styling and Layout

8. **Style Angular Material Components:**
   - Apply styles to enhance the visual appeal of the text-area question.
   - Ensure a consistent layout with other form elements.

### Step 8: Integration and Testing

9. **Integrate in a Sample Project:**
   - Create a sample Angular project to integrate and test the SL-Library with text-area questions.

10. **Test the Library:**
    - Test the library in the sample project to ensure that it renders the text-area form element correctly.

### Step 9: Review with Mentor

11. **Review with Mentor, Amoghavarsh:**
    - Share the implementation and documentation with the mentor for review.
    - Incorporate any feedback and make necessary adjustments.

### Step 10: Finalize and Release

12. **Finalize and Release:**
    - Address any remaining issues or improvements.
    - Release the SL-Library with text-area question support.

**Comment by sid-nc** [comment]
@kiranharidas187 Can I get assigned to this issue

**Comment by prakhardotdeb** [comment]
hello @kiranharidas187  sir! I feels i have skills required for this project and i would love to contributr. Could you please assign this ticket to me?

**Comment by sheffalee** [comment]
@kiranharidas187 can u assign me this task as this matches my skill sets and i would love to do this task

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by aryangandhi05** [comment]
Hare krishna @kiranharidas187 Sir I want to solve this issue, as i understand it, and i will give my 100% for solving this issue So please, can you assign me this?

**Comment by Guptasameer533** [comment]
Hi @kiranharidas187, I have read the project description in detail.

Therefore, as an experienced **Angular developer**, I possess the requisite skills to implement **the text-area as an element in form** and **API flows** effectively. My expertise lies in crafting **responsive designs**, **seamlessly integrating with APIs**, and conducting **comprehensive testing**. I am committed to delivering high-quality work that adheres to the project's standards.

Furthermore, I am eager to **collaborate** closely with the team to ensure a successful implementation of this feature.

**Comment by 2003sidd** [comment]
Hi @kiranharidas187 sir, I have read all the description and goals related to this issue and I want to solve this issue can you please assign this to me?

**Comment by PayalKumari10** [comment]
@kiranharidas187  i want to work on this issue plz assign me

**Comment by Mang0codes** [comment]
hey is this still open . Can I work on this?
